# Generated by Django 2.2.16 on 2022-08-19 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_auto_20220820_0123"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="title",
            options={
                "default_related_name": "titles",
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
    ]
